/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiRealtimeToolRouteImport } from './routes/api/realtime/tool'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime/session'
import { Route as ApiPublicWebSearchRouteImport } from './routes/api/public/web-search'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiIntegrationsMicrosoftStatusRouteImport } from './routes/api/integrations/microsoft/status'
import { Route as ApiIntegrationsMicrosoftDisconnectRouteImport } from './routes/api/integrations/microsoft/disconnect'
import { Route as ApiIntegrationsMicrosoftConnectRouteImport } from './routes/api/integrations/microsoft/connect'
import { Route as ApiIntegrationsMicrosoftCompleteRouteImport } from './routes/api/integrations/microsoft/complete'
import { Route as ApiIntegrationsMicrosoftCallbackRouteImport } from './routes/api/integrations/microsoft/callback'
import { Route as ApiPublicJarvisToolsSend_outlookRouteImport } from './routes/api/public/jarvis/tools/send_outlook'
import { Route as ApiPublicJarvisToolsSend_gmailRouteImport } from './routes/api/public/jarvis/tools/send_gmail'
import { Route as ApiPublicJarvisToolsSend_emailRouteImport } from './routes/api/public/jarvis/tools/send_email'
import { Route as ApiPublicJarvisToolsSearch_webRouteImport } from './routes/api/public/jarvis/tools/search_web'
import { Route as ApiPublicJarvisToolsRead_calendarRouteImport } from './routes/api/public/jarvis/tools/read_calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRealtimeToolRoute = ApiRealtimeToolRouteImport.update({
  id: '/api/realtime/tool',
  path: '/api/realtime/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime/session',
  path: '/api/realtime/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebSearchRoute = ApiPublicWebSearchRouteImport.update({
  id: '/api/public/web-search',
  path: '/api/public/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiIntegrationsMicrosoftStatusRoute =
  ApiIntegrationsMicrosoftStatusRouteImport.update({
    id: '/api/integrations/microsoft/status',
    path: '/api/integrations/microsoft/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMicrosoftDisconnectRoute =
  ApiIntegrationsMicrosoftDisconnectRouteImport.update({
    id: '/api/integrations/microsoft/disconnect',
    path: '/api/integrations/microsoft/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMicrosoftConnectRoute =
  ApiIntegrationsMicrosoftConnectRouteImport.update({
    id: '/api/integrations/microsoft/connect',
    path: '/api/integrations/microsoft/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMicrosoftCompleteRoute =
  ApiIntegrationsMicrosoftCompleteRouteImport.update({
    id: '/api/integrations/microsoft/complete',
    path: '/api/integrations/microsoft/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMicrosoftCallbackRoute =
  ApiIntegrationsMicrosoftCallbackRouteImport.update({
    id: '/api/integrations/microsoft/callback',
    path: '/api/integrations/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsSend_outlookRoute =
  ApiPublicJarvisToolsSend_outlookRouteImport.update({
    id: '/api/public/jarvis/tools/send_outlook',
    path: '/api/public/jarvis/tools/send_outlook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsSend_gmailRoute =
  ApiPublicJarvisToolsSend_gmailRouteImport.update({
    id: '/api/public/jarvis/tools/send_gmail',
    path: '/api/public/jarvis/tools/send_gmail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsSend_emailRoute =
  ApiPublicJarvisToolsSend_emailRouteImport.update({
    id: '/api/public/jarvis/tools/send_email',
    path: '/api/public/jarvis/tools/send_email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsSearch_webRoute =
  ApiPublicJarvisToolsSearch_webRouteImport.update({
    id: '/api/public/jarvis/tools/search_web',
    path: '/api/public/jarvis/tools/search_web',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsRead_calendarRoute =
  ApiPublicJarvisToolsRead_calendarRouteImport.update({
    id: '/api/public/jarvis/tools/read_calendar',
    path: '/api/public/jarvis/tools/read_calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/realtime/tool': typeof ApiRealtimeToolRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/microsoft/complete': typeof ApiIntegrationsMicrosoftCompleteRoute
  '/api/integrations/microsoft/connect': typeof ApiIntegrationsMicrosoftConnectRoute
  '/api/integrations/microsoft/disconnect': typeof ApiIntegrationsMicrosoftDisconnectRoute
  '/api/integrations/microsoft/status': typeof ApiIntegrationsMicrosoftStatusRoute
  '/api/public/jarvis/tools/read_calendar': typeof ApiPublicJarvisToolsRead_calendarRoute
  '/api/public/jarvis/tools/search_web': typeof ApiPublicJarvisToolsSearch_webRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
  '/api/public/jarvis/tools/send_gmail': typeof ApiPublicJarvisToolsSend_gmailRoute
  '/api/public/jarvis/tools/send_outlook': typeof ApiPublicJarvisToolsSend_outlookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/realtime/tool': typeof ApiRealtimeToolRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/microsoft/complete': typeof ApiIntegrationsMicrosoftCompleteRoute
  '/api/integrations/microsoft/connect': typeof ApiIntegrationsMicrosoftConnectRoute
  '/api/integrations/microsoft/disconnect': typeof ApiIntegrationsMicrosoftDisconnectRoute
  '/api/integrations/microsoft/status': typeof ApiIntegrationsMicrosoftStatusRoute
  '/api/public/jarvis/tools/read_calendar': typeof ApiPublicJarvisToolsRead_calendarRoute
  '/api/public/jarvis/tools/search_web': typeof ApiPublicJarvisToolsSearch_webRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
  '/api/public/jarvis/tools/send_gmail': typeof ApiPublicJarvisToolsSend_gmailRoute
  '/api/public/jarvis/tools/send_outlook': typeof ApiPublicJarvisToolsSend_outlookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/realtime/tool': typeof ApiRealtimeToolRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/integrations/microsoft/callback': typeof ApiIntegrationsMicrosoftCallbackRoute
  '/api/integrations/microsoft/complete': typeof ApiIntegrationsMicrosoftCompleteRoute
  '/api/integrations/microsoft/connect': typeof ApiIntegrationsMicrosoftConnectRoute
  '/api/integrations/microsoft/disconnect': typeof ApiIntegrationsMicrosoftDisconnectRoute
  '/api/integrations/microsoft/status': typeof ApiIntegrationsMicrosoftStatusRoute
  '/api/public/jarvis/tools/read_calendar': typeof ApiPublicJarvisToolsRead_calendarRoute
  '/api/public/jarvis/tools/search_web': typeof ApiPublicJarvisToolsSearch_webRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
  '/api/public/jarvis/tools/send_gmail': typeof ApiPublicJarvisToolsSend_gmailRoute
  '/api/public/jarvis/tools/send_outlook': typeof ApiPublicJarvisToolsSend_outlookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/quality'
    | '/contacts'
    | '/knowledge'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/web-search'
    | '/api/realtime/session'
    | '/api/realtime/tool'
    | '/chat/'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/microsoft/complete'
    | '/api/integrations/microsoft/connect'
    | '/api/integrations/microsoft/disconnect'
    | '/api/integrations/microsoft/status'
    | '/api/public/jarvis/tools/read_calendar'
    | '/api/public/jarvis/tools/search_web'
    | '/api/public/jarvis/tools/send_email'
    | '/api/public/jarvis/tools/send_gmail'
    | '/api/public/jarvis/tools/send_outlook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/quality'
    | '/contacts'
    | '/knowledge'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/web-search'
    | '/api/realtime/session'
    | '/api/realtime/tool'
    | '/chat'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/microsoft/complete'
    | '/api/integrations/microsoft/connect'
    | '/api/integrations/microsoft/disconnect'
    | '/api/integrations/microsoft/status'
    | '/api/public/jarvis/tools/read_calendar'
    | '/api/public/jarvis/tools/search_web'
    | '/api/public/jarvis/tools/send_email'
    | '/api/public/jarvis/tools/send_gmail'
    | '/api/public/jarvis/tools/send_outlook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/quality'
    | '/_authenticated/contacts'
    | '/_authenticated/knowledge'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/api/public/web-search'
    | '/api/realtime/session'
    | '/api/realtime/tool'
    | '/_authenticated/chat/'
    | '/api/integrations/microsoft/callback'
    | '/api/integrations/microsoft/complete'
    | '/api/integrations/microsoft/connect'
    | '/api/integrations/microsoft/disconnect'
    | '/api/integrations/microsoft/status'
    | '/api/public/jarvis/tools/read_calendar'
    | '/api/public/jarvis/tools/search_web'
    | '/api/public/jarvis/tools/send_email'
    | '/api/public/jarvis/tools/send_gmail'
    | '/api/public/jarvis/tools/send_outlook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicWebSearchRoute: typeof ApiPublicWebSearchRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiRealtimeToolRoute: typeof ApiRealtimeToolRoute
  ApiIntegrationsMicrosoftCallbackRoute: typeof ApiIntegrationsMicrosoftCallbackRoute
  ApiIntegrationsMicrosoftCompleteRoute: typeof ApiIntegrationsMicrosoftCompleteRoute
  ApiIntegrationsMicrosoftConnectRoute: typeof ApiIntegrationsMicrosoftConnectRoute
  ApiIntegrationsMicrosoftDisconnectRoute: typeof ApiIntegrationsMicrosoftDisconnectRoute
  ApiIntegrationsMicrosoftStatusRoute: typeof ApiIntegrationsMicrosoftStatusRoute
  ApiPublicJarvisToolsRead_calendarRoute: typeof ApiPublicJarvisToolsRead_calendarRoute
  ApiPublicJarvisToolsSearch_webRoute: typeof ApiPublicJarvisToolsSearch_webRoute
  ApiPublicJarvisToolsSend_emailRoute: typeof ApiPublicJarvisToolsSend_emailRoute
  ApiPublicJarvisToolsSend_gmailRoute: typeof ApiPublicJarvisToolsSend_gmailRoute
  ApiPublicJarvisToolsSend_outlookRoute: typeof ApiPublicJarvisToolsSend_outlookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/realtime/tool': {
      id: '/api/realtime/tool'
      path: '/api/realtime/tool'
      fullPath: '/api/realtime/tool'
      preLoaderRoute: typeof ApiRealtimeToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/session': {
      id: '/api/realtime/session'
      path: '/api/realtime/session'
      fullPath: '/api/realtime/session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/web-search': {
      id: '/api/public/web-search'
      path: '/api/public/web-search'
      fullPath: '/api/public/web-search'
      preLoaderRoute: typeof ApiPublicWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/integrations/microsoft/status': {
      id: '/api/integrations/microsoft/status'
      path: '/api/integrations/microsoft/status'
      fullPath: '/api/integrations/microsoft/status'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/microsoft/disconnect': {
      id: '/api/integrations/microsoft/disconnect'
      path: '/api/integrations/microsoft/disconnect'
      fullPath: '/api/integrations/microsoft/disconnect'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/microsoft/connect': {
      id: '/api/integrations/microsoft/connect'
      path: '/api/integrations/microsoft/connect'
      fullPath: '/api/integrations/microsoft/connect'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/microsoft/complete': {
      id: '/api/integrations/microsoft/complete'
      path: '/api/integrations/microsoft/complete'
      fullPath: '/api/integrations/microsoft/complete'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/microsoft/callback': {
      id: '/api/integrations/microsoft/callback'
      path: '/api/integrations/microsoft/callback'
      fullPath: '/api/integrations/microsoft/callback'
      preLoaderRoute: typeof ApiIntegrationsMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/send_outlook': {
      id: '/api/public/jarvis/tools/send_outlook'
      path: '/api/public/jarvis/tools/send_outlook'
      fullPath: '/api/public/jarvis/tools/send_outlook'
      preLoaderRoute: typeof ApiPublicJarvisToolsSend_outlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/send_gmail': {
      id: '/api/public/jarvis/tools/send_gmail'
      path: '/api/public/jarvis/tools/send_gmail'
      fullPath: '/api/public/jarvis/tools/send_gmail'
      preLoaderRoute: typeof ApiPublicJarvisToolsSend_gmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/send_email': {
      id: '/api/public/jarvis/tools/send_email'
      path: '/api/public/jarvis/tools/send_email'
      fullPath: '/api/public/jarvis/tools/send_email'
      preLoaderRoute: typeof ApiPublicJarvisToolsSend_emailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/search_web': {
      id: '/api/public/jarvis/tools/search_web'
      path: '/api/public/jarvis/tools/search_web'
      fullPath: '/api/public/jarvis/tools/search_web'
      preLoaderRoute: typeof ApiPublicJarvisToolsSearch_webRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/read_calendar': {
      id: '/api/public/jarvis/tools/read_calendar'
      path: '/api/public/jarvis/tools/read_calendar'
      fullPath: '/api/public/jarvis/tools/read_calendar'
      preLoaderRoute: typeof ApiPublicJarvisToolsRead_calendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicWebSearchRoute: ApiPublicWebSearchRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiRealtimeToolRoute: ApiRealtimeToolRoute,
  ApiIntegrationsMicrosoftCallbackRoute: ApiIntegrationsMicrosoftCallbackRoute,
  ApiIntegrationsMicrosoftCompleteRoute: ApiIntegrationsMicrosoftCompleteRoute,
  ApiIntegrationsMicrosoftConnectRoute: ApiIntegrationsMicrosoftConnectRoute,
  ApiIntegrationsMicrosoftDisconnectRoute:
    ApiIntegrationsMicrosoftDisconnectRoute,
  ApiIntegrationsMicrosoftStatusRoute: ApiIntegrationsMicrosoftStatusRoute,
  ApiPublicJarvisToolsRead_calendarRoute:
    ApiPublicJarvisToolsRead_calendarRoute,
  ApiPublicJarvisToolsSearch_webRoute: ApiPublicJarvisToolsSearch_webRoute,
  ApiPublicJarvisToolsSend_emailRoute: ApiPublicJarvisToolsSend_emailRoute,
  ApiPublicJarvisToolsSend_gmailRoute: ApiPublicJarvisToolsSend_gmailRoute,
  ApiPublicJarvisToolsSend_outlookRoute: ApiPublicJarvisToolsSend_outlookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
