/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicWebSearchRouteImport } from './routes/api/public/web-search'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicMsOauthCallbackRouteImport } from './routes/api/public/ms-oauth/callback'
import { Route as ApiPublicJarvisToolsSend_emailRouteImport } from './routes/api/public/jarvis/tools/send_email'
import { Route as ApiPublicJarvisToolsRespond_calendar_eventRouteImport } from './routes/api/public/jarvis/tools/respond_calendar_event'
import { Route as ApiPublicJarvisToolsList_calendar_eventsRouteImport } from './routes/api/public/jarvis/tools/list_calendar_events'
import { Route as ApiPublicJarvisToolsCreate_calendar_eventRouteImport } from './routes/api/public/jarvis/tools/create_calendar_event'
import { Route as ApiPublicJarvisToolsCancel_calendar_eventRouteImport } from './routes/api/public/jarvis/tools/cancel_calendar_event'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebSearchRoute = ApiPublicWebSearchRouteImport.update({
  id: '/api/public/web-search',
  path: '/api/public/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMsOauthCallbackRoute =
  ApiPublicMsOauthCallbackRouteImport.update({
    id: '/api/public/ms-oauth/callback',
    path: '/api/public/ms-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsSend_emailRoute =
  ApiPublicJarvisToolsSend_emailRouteImport.update({
    id: '/api/public/jarvis/tools/send_email',
    path: '/api/public/jarvis/tools/send_email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsRespond_calendar_eventRoute =
  ApiPublicJarvisToolsRespond_calendar_eventRouteImport.update({
    id: '/api/public/jarvis/tools/respond_calendar_event',
    path: '/api/public/jarvis/tools/respond_calendar_event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsList_calendar_eventsRoute =
  ApiPublicJarvisToolsList_calendar_eventsRouteImport.update({
    id: '/api/public/jarvis/tools/list_calendar_events',
    path: '/api/public/jarvis/tools/list_calendar_events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsCreate_calendar_eventRoute =
  ApiPublicJarvisToolsCreate_calendar_eventRouteImport.update({
    id: '/api/public/jarvis/tools/create_calendar_event',
    path: '/api/public/jarvis/tools/create_calendar_event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJarvisToolsCancel_calendar_eventRoute =
  ApiPublicJarvisToolsCancel_calendar_eventRouteImport.update({
    id: '/api/public/jarvis/tools/cancel_calendar_event',
    path: '/api/public/jarvis/tools/cancel_calendar_event',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/ms-oauth/callback': typeof ApiPublicMsOauthCallbackRoute
  '/api/public/jarvis/tools/cancel_calendar_event': typeof ApiPublicJarvisToolsCancel_calendar_eventRoute
  '/api/public/jarvis/tools/create_calendar_event': typeof ApiPublicJarvisToolsCreate_calendar_eventRoute
  '/api/public/jarvis/tools/list_calendar_events': typeof ApiPublicJarvisToolsList_calendar_eventsRoute
  '/api/public/jarvis/tools/respond_calendar_event': typeof ApiPublicJarvisToolsRespond_calendar_eventRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/ms-oauth/callback': typeof ApiPublicMsOauthCallbackRoute
  '/api/public/jarvis/tools/cancel_calendar_event': typeof ApiPublicJarvisToolsCancel_calendar_eventRoute
  '/api/public/jarvis/tools/create_calendar_event': typeof ApiPublicJarvisToolsCreate_calendar_eventRoute
  '/api/public/jarvis/tools/list_calendar_events': typeof ApiPublicJarvisToolsList_calendar_eventsRoute
  '/api/public/jarvis/tools/respond_calendar_event': typeof ApiPublicJarvisToolsRespond_calendar_eventRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/web-search': typeof ApiPublicWebSearchRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/ms-oauth/callback': typeof ApiPublicMsOauthCallbackRoute
  '/api/public/jarvis/tools/cancel_calendar_event': typeof ApiPublicJarvisToolsCancel_calendar_eventRoute
  '/api/public/jarvis/tools/create_calendar_event': typeof ApiPublicJarvisToolsCreate_calendar_eventRoute
  '/api/public/jarvis/tools/list_calendar_events': typeof ApiPublicJarvisToolsList_calendar_eventsRoute
  '/api/public/jarvis/tools/respond_calendar_event': typeof ApiPublicJarvisToolsRespond_calendar_eventRoute
  '/api/public/jarvis/tools/send_email': typeof ApiPublicJarvisToolsSend_emailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/contacts'
    | '/knowledge'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/api/public/web-search'
    | '/chat/'
    | '/api/public/ms-oauth/callback'
    | '/api/public/jarvis/tools/cancel_calendar_event'
    | '/api/public/jarvis/tools/create_calendar_event'
    | '/api/public/jarvis/tools/list_calendar_events'
    | '/api/public/jarvis/tools/respond_calendar_event'
    | '/api/public/jarvis/tools/send_email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/contacts'
    | '/knowledge'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/api/public/web-search'
    | '/chat'
    | '/api/public/ms-oauth/callback'
    | '/api/public/jarvis/tools/cancel_calendar_event'
    | '/api/public/jarvis/tools/create_calendar_event'
    | '/api/public/jarvis/tools/list_calendar_events'
    | '/api/public/jarvis/tools/respond_calendar_event'
    | '/api/public/jarvis/tools/send_email'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/activity'
    | '/_authenticated/contacts'
    | '/_authenticated/knowledge'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$threadId'
    | '/api/public/web-search'
    | '/_authenticated/chat/'
    | '/api/public/ms-oauth/callback'
    | '/api/public/jarvis/tools/cancel_calendar_event'
    | '/api/public/jarvis/tools/create_calendar_event'
    | '/api/public/jarvis/tools/list_calendar_events'
    | '/api/public/jarvis/tools/respond_calendar_event'
    | '/api/public/jarvis/tools/send_email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebSearchRoute: typeof ApiPublicWebSearchRoute
  ApiPublicMsOauthCallbackRoute: typeof ApiPublicMsOauthCallbackRoute
  ApiPublicJarvisToolsCancel_calendar_eventRoute: typeof ApiPublicJarvisToolsCancel_calendar_eventRoute
  ApiPublicJarvisToolsCreate_calendar_eventRoute: typeof ApiPublicJarvisToolsCreate_calendar_eventRoute
  ApiPublicJarvisToolsList_calendar_eventsRoute: typeof ApiPublicJarvisToolsList_calendar_eventsRoute
  ApiPublicJarvisToolsRespond_calendar_eventRoute: typeof ApiPublicJarvisToolsRespond_calendar_eventRoute
  ApiPublicJarvisToolsSend_emailRoute: typeof ApiPublicJarvisToolsSend_emailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/web-search': {
      id: '/api/public/web-search'
      path: '/api/public/web-search'
      fullPath: '/api/public/web-search'
      preLoaderRoute: typeof ApiPublicWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ms-oauth/callback': {
      id: '/api/public/ms-oauth/callback'
      path: '/api/public/ms-oauth/callback'
      fullPath: '/api/public/ms-oauth/callback'
      preLoaderRoute: typeof ApiPublicMsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/send_email': {
      id: '/api/public/jarvis/tools/send_email'
      path: '/api/public/jarvis/tools/send_email'
      fullPath: '/api/public/jarvis/tools/send_email'
      preLoaderRoute: typeof ApiPublicJarvisToolsSend_emailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/respond_calendar_event': {
      id: '/api/public/jarvis/tools/respond_calendar_event'
      path: '/api/public/jarvis/tools/respond_calendar_event'
      fullPath: '/api/public/jarvis/tools/respond_calendar_event'
      preLoaderRoute: typeof ApiPublicJarvisToolsRespond_calendar_eventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/list_calendar_events': {
      id: '/api/public/jarvis/tools/list_calendar_events'
      path: '/api/public/jarvis/tools/list_calendar_events'
      fullPath: '/api/public/jarvis/tools/list_calendar_events'
      preLoaderRoute: typeof ApiPublicJarvisToolsList_calendar_eventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/create_calendar_event': {
      id: '/api/public/jarvis/tools/create_calendar_event'
      path: '/api/public/jarvis/tools/create_calendar_event'
      fullPath: '/api/public/jarvis/tools/create_calendar_event'
      preLoaderRoute: typeof ApiPublicJarvisToolsCreate_calendar_eventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jarvis/tools/cancel_calendar_event': {
      id: '/api/public/jarvis/tools/cancel_calendar_event'
      path: '/api/public/jarvis/tools/cancel_calendar_event'
      fullPath: '/api/public/jarvis/tools/cancel_calendar_event'
      preLoaderRoute: typeof ApiPublicJarvisToolsCancel_calendar_eventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebSearchRoute: ApiPublicWebSearchRoute,
  ApiPublicMsOauthCallbackRoute: ApiPublicMsOauthCallbackRoute,
  ApiPublicJarvisToolsCancel_calendar_eventRoute:
    ApiPublicJarvisToolsCancel_calendar_eventRoute,
  ApiPublicJarvisToolsCreate_calendar_eventRoute:
    ApiPublicJarvisToolsCreate_calendar_eventRoute,
  ApiPublicJarvisToolsList_calendar_eventsRoute:
    ApiPublicJarvisToolsList_calendar_eventsRoute,
  ApiPublicJarvisToolsRespond_calendar_eventRoute:
    ApiPublicJarvisToolsRespond_calendar_eventRoute,
  ApiPublicJarvisToolsSend_emailRoute: ApiPublicJarvisToolsSend_emailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
